//answer=window.prompt("Wis?");

document.getElementById("message").innerHTML="This is generated by Javascript";
hide();


function hide() {
  document.getElementById('description').style.visibility='hidden';
}